networks:
  restaurant_network:
    driver: bridge

volumes:
  # ms_auth
  ms_auth_db_data:
  ms_auth_cache:
  # ms_menu
  ms_menu_db_data:
  ms_menu_cache:
  # ms_order
  ms_order_db_data:
  ms_order_cache:
  # common
  rabbitmq_data:
  minio_data:
  # test_db:

services:
  # ==========================================
  # ИНФРАСТРУКТУРА (Общая)
  # ==========================================
  traefik:
    image: traefik:v3.6
    container_name: traefik
    networks:
      - restaurant_network
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      # - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.traefik.rule=Host(`dashboard.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"



  rabbitmq:
    image: rabbitmq:4-management
    container_name: shared_rabbitmq
    networks:
      - restaurant_network
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  s3:
    image: minio/minio
    container_name: shared_minio
    networks:
      - restaurant_network
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  # test_db:
  #   image: postgres:15-alpine
  #   container_name: test_db
  #   networks:
  #     - restaurant_network
  #   ports:
  #     - "5433:5432"
  #   env:
  #     - ./services/ms_auth/.env.dev
  #   volumes:
  #     - test_db_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # ==========================================
  # MS: AUTH
  # ==========================================
  ms_auth_api:
    build:
      context: ./services/ms_auth
      dockerfile: Dockerfile
    container_name: ms_auth_api
    volumes:
      - ./services/ms_auth:/app
    networks:
      - restaurant_network
    env_file:
      - ./services/ms_auth/.env.dev
    depends_on:
      ms_auth_db:
        condition: service_healthy
    # ports: # закрываем порты потому что теперь этим будет заниматься traefik
    #   - "8001:8000"
    labels:
      - "traefik.enable=true"

      # middleware traefik для переадресации на сервис авторизации при попытке попасть на защищеный сервис
      - "traefik.http.middlewares.gateway_auth.forwardauth.address=http://ms_auth_api:8000/auth/verify"
      - "traefik.http.middlewares.gateway_auth.forwardauth.authResponseHeaders=X-User-Id,X-Is-Superuser"
      - "traefik.http.middlewares.gateway_auth.forwardauth.trustForwardHeader=true"
      # middleware traefik для глобального ограничения количества возможных запросов на сервис
      - "traefik.http.middlewares.service_rate_limiter.ratelimit.average=10"
      - "traefik.http.middlewares.service_rate_limiter.ratelimit.burst=50"

      - "traefik.http.services.ms_auth_api.loadbalancer.server.port=8000"

      # public
      - "traefik.http.routers.ms_auth_api_public.rule=Host(`auth.localhost`) && (PathPrefix(`/docs`) || PathPrefix(`/openapi.json`))"
      - "traefik.http.routers.ms_auth_api_public.service=ms_auth_api"
      # protected
      - "traefik.http.routers.ms_auth_api_protected.rule=Host(`auth.localhost`)"
      - "traefik.http.routers.ms_auth_api_protected.service=ms_auth_api"
      - "traefik.http.routers.ms_auth_api_protected.middlewares=service_rate_limiter"

  ms_auth_db:
    image: postgres:15-alpine
    container_name: ms_auth_db
    networks:
      - restaurant_network
    ports:
      - "5433:5432"
    env_file:
      - ./services/ms_auth/.env.dev
    volumes:
      - ms_auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms_auth_cache:
    image: redis:7-alpine
    container_name: ms_auth_cache
    networks:
      - restaurant_network
    volumes:
      - ms_auth_cache:/cache_data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  # MS: MENU
  # ==========================================
  ms_menu_api:
    build:
      context: ./services/ms_menu
      dockerfile: Dockerfile
    container_name: ms_menu_api
    networks:
      - restaurant_network
    volumes:
      - ./services/ms_menu:/app
    env_file:
      - ./services/ms_menu/.env.dev
    depends_on:
      ms_menu_db:
        condition: service_healthy
      ms_menu_cache:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    # ports:
    #   - "8002:8000"
    labels:
      - "traefik.enable=true"

      - "traefik.http.services.ms_menu_api.loadbalancer.server.port=8000"

      - "traefik.http.routers.ms_menu_api_public.rule=Host(`menu.localhost`) && (PathPrefix(`/docs`) || PathPrefix(`/openapi.json`))"
      - "traefik.http.routers.ms_menu_api_public.service=ms_menu_api"

      - "traefik.http.routers.ms_menu_api_protected.rule=Host(`menu.localhost`)"
      - "traefik.http.routers.ms_menu_api_protected.service=ms_menu_api"
      - "traefik.http.routers.ms_menu_api_protected.middlewares=gateway_auth,service_rate_limiter"

  ms_menu_worker:
    build:
      context: ./services/ms_menu
      dockerfile: Dockerfile
    container_name: ms_menu_worker
    networks:
      - restaurant_network
    volumes:
      - ./services/ms_menu:/app
    env_file:
      - ./services/ms_menu/.env.dev
    depends_on:
      ms_menu_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: ["python", "-m", "worker"]

  ms_menu_db:
    image: postgres:15-alpine
    container_name: ms_menu_db
    networks:
      - restaurant_network
    ports:
      - "5434:5432"
    env_file:
      - ./services/ms_menu/.env.dev
    volumes:
      - ms_menu_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms_menu_cache:
    image: redis:7-alpine
    container_name: ms_menu_cache
    networks:
      - restaurant_network
    volumes:
      - ms_menu_cache:/cache_data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  # MS: ORDER
  # ==========================================
  ms_order_api:
    build:
      context: ./services/ms_order
      dockerfile: Dockerfile
    container_name: ms_order_api
    networks:
      - restaurant_network
    volumes:
      - ./services/ms_order:/app
    env_file:
      - ./services/ms_order/.env.dev
    depends_on:
      ms_order_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    # ports:
    #   - "8003:8000"
    labels:
      - "traefik.enable=true"

      - "traefik.http.services.ms_order_api.loadbalancer.server.port=8000"

      - "traefik.http.routers.ms_order_api_public.rule=Host(`order.localhost`)" #&& (PathPrefix(`/docs`) || PathPrefix(`/openapi.json`))"
      # - "traefik.http.routers.ms_order_api_public.service=ms_order_api"

      # - "traefik.http.routers.ms_order_api_protected.rule=Host(`order.localhost`)"
      # - "traefik.http.routers.ms_order_api_protected.service=ms_order_api"
      # - "traefik.http.routers.ms_order_api_protected.middlewares=gateway_auth,service_rate_limiter"

  ms_order_worker:
    build:
      context: ./services/ms_order
      dockerfile: Dockerfile
    container_name: ms_order_worker
    networks:
      - restaurant_network
    volumes:
      - ./services/ms_order:/app
    env_file:
      - ./services/ms_order/.env.dev
    depends_on:
      ms_menu_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: ["python", "-m", "worker"]

  ms_order_db:
    image: postgres:15-alpine
    container_name: ms_order_db
    networks:
      - restaurant_network
    ports:
      - "5435:5432"
    env_file:
      - ./services/ms_order/.env.dev
    volumes:
      - ms_order_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms_order_cache:
    image: redis:7-alpine
    container_name: ms_order_cache
    networks:
      - restaurant_network
    volumes:
      - ms_order_cache:/cache_data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  # ==========================================
  # MS: PAYMENT
  # ==========================================
  ms_payment_api:
    build:
      context: ./services/ms_payment
      dockerfile: Dockerfile
    container_name: ms_payment_api
    networks:
      - restaurant_network
    volumes:
      - ./services/ms_payment:/app
    env_file:
      - ./services/ms_payment/.env.dev
    depends_on:
      ms_order_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    labels:
      - "traefik.enable=true"

      - "traefik.http.services.ms_payment_api.loadbalancer.server.port=8000"

      - "traefik.http.routers.ms_payment_api_public.rule=Host(`payment.localhost`)"