"""empty message

Revision ID: 878631496c5f
Revises: f300d5c17f41
Create Date: 2026-02-20 02:34:54.896018

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "878631496c5f"
down_revision: Union[str, Sequence[str], None] = "f300d5c17f41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
