"""empty message

Revision ID: db308930c80d
Revises: 63465ec2d737
Create Date: 2026-02-20 01:34:07.134273

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db308930c80d"
down_revision: Union[str, Sequence[str], None] = "63465ec2d737"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("efresh_token", sa.String(), nullable=True))
    op.add_column("users", sa.Column("token_expires_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "token_expires_at")
    op.drop_column("users", "efresh_token")
    # ### end Alembic commands ###
