"""empty message

Revision ID: f300d5c17f41
Revises: db308930c80d
Create Date: 2026-02-20 02:14:37.969825

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f300d5c17f41"
down_revision: Union[str, Sequence[str], None] = "db308930c80d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "phone_verifications", sa.Column("max_attempts", sa.Integer(), nullable=False)
    )
    op.add_column("users", sa.Column("refresh_token", sa.String(), nullable=True))
    op.drop_column("users", "efresh_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("efresh_token", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("users", "refresh_token")
    op.drop_column("phone_verifications", "max_attempts")
    # ### end Alembic commands ###
