"""new column image_url for dish

Revision ID: 1c247a06d588
Revises: 6910e1c05d23
Create Date: 2026-03-11 18:37:01.557617

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c247a06d588"
down_revision: Union[str, Sequence[str], None] = "6910e1c05d23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dishes", sa.Column("image_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dishes", "image_url")
    # ### end Alembic commands ###
