"""new column is_available

Revision ID: 8a37254d0997
Revises: 4b7a9bcfbca9
Create Date: 2026-03-01 22:46:58.620024

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a37254d0997"
down_revision: Union[str, Sequence[str], None] = "4b7a9bcfbca9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dishes",
        sa.Column("is_available", sa.Boolean(), server_default="True", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dishes", "is_available")
    # ### end Alembic commands ###
