"""category_id is no nullable

Revision ID: 9308a2c41700
Revises: 8a37254d0997
Create Date: 2026-03-02 17:41:55.544722

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9308a2c41700"
down_revision: Union[str, Sequence[str], None] = "8a37254d0997"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dishes", "category_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(op.f("dishes_category_id_fkey"), "dishes", type_="foreignkey")
    op.create_foreign_key(
        None, "dishes", "categories", ["category_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "dishes", type_="foreignkey")
    op.create_foreign_key(
        op.f("dishes_category_id_fkey"),
        "dishes",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("dishes", "category_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
